In [97]:
#import libraries
import matplotlib.pyplot as plt # import of matplotlib
import numpy as np # import of numpy
from numpy import linalg as LA
%matplotlib inline

from PyQuante.Molecule import Molecule
from PyQuante.Ints import *

In [107]:
#Molekül H2

mol1 = Molecule('H2',[(1,(0,0,0)),(1,(1.4,0,0))])
bfs = getbasis(mol1.atoms,'sto-3g')

S,h = get1ints(bfs,mol1.atoms)
t = getT(bfs)
v = getV(bfs,mol1.atoms)	
Inttwo = get2ints(bfs)  #das ist unser g (Lüchow-Notation) 
Hcore = t + v  #initial guess: F = Hcore

Elec = 2 #nachgucken wie man allgemein an Anzahl der Elektronen kommt
occs = Elec/2

print mol1[0]

print bfs #WTF????????????

print Inttwo


#[0.7746059413378763, 0.44410765642363825, 0.29702853968824644, 0.5696759199791712, 0.44410765642363825, 0.7746059413378763]
# 0000                      1000                   1010                  0011              1110                1111

Inttwo[0]


Atom ID: 0 Atomic Num:  1 ( 0.000, 0.000, 0.000)
array('d', [0.7746059413378763, 0.44410765642363825, 0.29702853968824644, 0.5696759199791712, 0.44410765642363825, 0.7746059413378763])


0.7746059413378763

In [99]:
print S
print Hcore
print Inttwo
	
s = LA.eigvals(S)
print s


[[ 1.          0.65931821]
 [ 0.65931821  1.        ]]
[[-1.12040901 -0.95837996]
 [-0.95837996 -1.12040901]]
array('d', [0.7746059413378763, 0.44410765642363825, 0.29702853968824644, 0.5696759199791712, 0.44410765642363825, 0.7746059413378763])
[ 1.65931821  0.34068179]


In [100]:
U = np.array([[2.**(-0.5), 2.**(-0.5)], [2.**(-0.5), -2.**(-0.5)]])
print U

print s
s_diag = np.array([[s[0], 0], [0, s[1]]])
print s_diag

X = U*s_diag
print X

F_trans = (X*Hcore)*X #orthogonalisierung
print F_trans

F = LA.eig(F_trans)[1] #[0] = Eigenwerte, [1] = Eigenvektoren
print F

C_trans = X*F
print C_trans

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[ 1.65931821  0.34068179]
[[ 1.65931821  0.        ]
 [ 0.          0.34068179]]
[[ 1.17331516  0.        ]
 [ 0.         -0.24089841]]
[[-1.54243174 -0.        ]
 [-0.         -0.06501962]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.17331516  0.        ]
 [ 0.         -0.24089841]]


In [101]:
#D-Matrix aufstellen

#bfs = 1
#occs = 1

D = np.array([[0.0, 0.0], [0.0, 0.0]])

for mu in range(0, 2): #bfs, ausgeschlossene Grenzen, daher bis 2
    for nu in range(0, 2): #bfs
        for i in range(0, 2): #bfs
             D[mu, nu] += 2*C_trans[mu, i]*C_trans[nu, i]

print D

[[ 2.75333691  0.        ]
 [ 0.          0.11606408]]


In [102]:
#F-Matrix aufstellen

F = Hcore

for mu in range(0, 2):      #if schleife in for-schleife?
    for nu in range(0, 2):
        for lam in range(0, 2):
            for sig in range(0, 2):
                F[mu, nu] += D[lam, sig]*Inttwo[zahl]#Inttwo(mu,nu,lam,sig)-0.5Inttwo(mu,sig,lam,nu)

SyntaxError: invalid syntax (<ipython-input-102-8caf8c391f4b>, line 9)