In [59]:
#import libraries
import matplotlib.pyplot as plt # import of matplotlib
import numpy as np # import of numpy
from numpy import linalg as LA
%matplotlib inline

from PyQuante.Molecule import Molecule
from PyQuante.Ints import *

In [60]:
#Molekül H2

mol1 = Molecule('H2',[(1,(0,0,0)),(1,(1.4,0,0))])
bfs = getbasis(mol1.atoms,'sto-3g')

S,h = get1ints(bfs,mol1.atoms)
t = getT(bfs)
v = getV(bfs,mol1.atoms)	
Inttwo = get2ints(bfs)  #das ist unser g (Lüchow-Notation) 
Hcore = t + v  #initial guess: F = Hcore

Elec = 2 #nachgucken wie man allgemein an Anzahl der Elektronen kommt
occs = Elec/2

print mol1[0]

print bfs #WTF????????????

print Inttwo


#[0.7746059413378763, 0.44410765642363825, 0.29702853968824644, 0.5696759199791712, 0.44410765642363825, 0.7746059413378763]
# 0000                      1000                   1010                  0011              1110                1111

Inttwo[0]


Atom ID: 0 Atomic Num:  1 ( 0.000, 0.000, 0.000)
array('d', [0.7746059413378763, 0.44410765642363825, 0.29702853968824644, 0.5696759199791712, 0.44410765642363825, 0.7746059413378763])


0.7746059413378763

In [61]:
print S
print Hcore
print Inttwo
	
s = LA.eigvals(S)
print s


[[ 1.          0.65931821]
 [ 0.65931821  1.        ]]
[[-1.12040901 -0.95837996]
 [-0.95837996 -1.12040901]]
array('d', [0.7746059413378763, 0.44410765642363825, 0.29702853968824644, 0.5696759199791712, 0.44410765642363825, 0.7746059413378763])
[ 1.65931821  0.34068179]


In [62]:
U = np.array([[2.**(-0.5), 2.**(-0.5)], [2.**(-0.5), -2.**(-0.5)]])
print U

print s
s_diag = np.array([[s[0]**(-0.5), 0], [0, s[1]**(-0.5)]])
print s_diag

X = np.dot(U,s_diag)
Xs = X.T
print X
print Xs

F_trans = np.dot(Xs,F) #orthogonalisierung
F_trans = np.dot(F_trans,X)
print F_trans

F = LA.eig(F_trans)[1] #[0] = Eigenwerte, [1] = Eigenvektoren
print F

C_trans = np.dot(X,F)
print C_trans

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[ 1.65931821  0.34068179]
[[ 0.77630996  0.        ]
 [ 0.          1.71326892]]
[[ 0.54893404  1.21146407]
 [ 0.54893404 -1.21146407]]
[[ 0.54893404  0.54893404]
 [ 1.21146407 -1.21146407]]
[[  9.63911069e-02   2.77555756e-17]
 [ -3.33066907e-16   1.81613779e+00]]
[[  1.00000000e+00   1.61393396e-17]
 [  0.00000000e+00   1.00000000e+00]]
[[ 0.54893404  1.21146407]
 [ 0.54893404 -1.21146407]]


In [63]:
#D-Matrix aufstellen

#bfs = 1
#occs = 1

D = np.array([[0.0, 0.0], [0.0, 0.0]])

G = np.array([[0.0, 0.0], [0.0, 0.0]])

for mu in range(0, 2): #bfs, ausgeschlossene Grenzen, daher bis 2
    for nu in range(0, 2): #bfs
             D[mu, nu] += 2*C_trans[mu, 0]*C_trans[nu, 0]

print D

[[ 0.60265716  0.60265716]
 [ 0.60265716  0.60265716]]


In [64]:
#F-Matrix aufstellen


for mu in range(0, 2):      #if schleife in for-schleife?
    for nu in range(0, 2):
        for lam in range(0, 2):
            for sig in range(0, 2):
                if mu == 0 and nu == 0 and lam == 0 and sig == 0:
                    A = Inttwo[0]
                    B = Inttwo[0]
                if mu == 0 and nu == 1 and lam == 0 and sig == 0:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 0 and nu == 0 and lam == 1 and sig == 0:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 0 and nu == 0 and lam == 0 and sig == 1:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 0 and nu == 1 and lam == 1 and sig == 0:
                    A = Inttwo[2]
                    B = Inttwo[2]
                if mu == 0 and nu == 1 and lam == 0 and sig == 1:
                    A = Inttwo[2]
                    B = Inttwo[3]
                if mu == 0 and nu == 1 and lam == 1 and sig == 1:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 1 and nu == 1 and lam == 1 and sig == 1:
                    A = Inttwo[0]
                    B = Inttwo[0]
                if mu == 0 and nu == 0 and lam == 1 and sig == 1:
                    A = Inttwo[3]
                    B = Inttwo[2]
                if mu == 1 and nu == 0 and lam == 1 and sig == 0:
                    A = Inttwo[2]
                    B = Inttwo[3]
                if mu == 1 and nu == 1 and lam == 0 and sig == 1:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 1 and nu == 1 and lam == 1 and sig == 0:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 1 and nu == 0 and lam == 1 and sig == 1:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 1 and nu == 1 and lam == 0 and sig == 0:
                    A = Inttwo[3]
                    B = Inttwo[2]
                if mu == 1 and nu == 0 and lam == 0 and sig == 0:
                    A = Inttwo[1]
                    B = Inttwo[1]
                if mu == 1 and nu == 0 and lam == 0 and sig == 1:
                    A = Inttwo[2]
                    B = Inttwo[2]
                    
                G[mu, nu] += D[lam, sig]*(A-0.5*B)
                
                F = Hcore + G
                    
print F

E = 0

for mu in range(0, 2):
    for nu in range(0, 2):
        E += 0.5*D[mu, nu]*(F[mu, nu]+Hcore[mu, nu])

        
print
print E + (1/1.4)


[[-0.36553735 -0.59388537]
 [-0.59388537 -0.36553735]]

-1.11671431622


In [ ]:
# SCF Iteration