In [5]:
#import libraries
import matplotlib.pyplot as plt # import of matplotlib
import numpy as np # import of numpy
from numpy import linalg as LA
%matplotlib inline

from PyQuante.Molecule import Molecule
from PyQuante.Ints import *

In [4]:
#Molekül H2

mol1 = Molecule('H2',[(1,(0,0,0)),(1,(1.4,0,0))])
bfs = getbasis(mol1.atoms,'sto-3g')

Sone,hone = get1ints(bfs,mol1.atoms)
tone = getT(bfs)
vone = getV(bfs,mol1.atoms)	
Inttwo = get2ints(bfs)     #das ist unser g (Lüchow-Notation) 
Hcore = tone + vone


In [6]:
print Sone
print Hcore
print Inttwo
	
sone = LA.eigvals(Sone)
print sone


[[ 1.          0.65931821]
 [ 0.65931821  1.        ]]
[[-1.12040901 -0.95837996]
 [-0.95837996 -1.12040901]]
array('d', [0.7746059413378763, 0.44410765642363825, 0.29702853968824644, 0.5696759199791712, 0.44410765642363825, 0.7746059413378763])
[ 1.65931821  0.34068179]


In [16]:
U = np.array([[2.**(0.5), 2.**(0.5)], [2.**(0.5), 2.**(-0.5)]])

In [17]:
print U

[[ 1.41421356  1.41421356]
 [ 1.41421356  0.70710678]]
